repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-absolute-import
        - flake8-black
        - flake8-docstrings
        - Flake8-pyproject
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-byte-order-marker
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
