name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip wheel twine
    - uses: cycjimmy/semantic-release-action@v4
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: Bryan Larson
        GIT_AUTHOR_EMAIL: bryan_larson@hms.harvard.edu
      with:
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/changelog
          @semantic-release/git
    - name: Publish to PyPi
      if: steps.semantic.outputs.new_release_published == 'true'
      env:
        PYPI_USERNAME: ${{ secrets.BLHMSDBMI_PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.BLHMSDBMI_PYPI_PASSWORD }}
      run: |
        twine upload --non-interactive -u "${PYPI_USERNAME}" -p "${PYPI_PASSWORD}" dist/*
